# -*- coding: utf-8 -*-
"""BIB3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12483LgCi49TyHUfDq6MYUuBqBmC29kII

Задание 1
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np

# %matplotlib inline

x = [1, 2, 3, 4, 5, 6, 7]
y = [3.5, 3.8, 4.2, 4.5, 5, 5.5, 7]

plt.plot(x, y)
plt.show()

plt.scatter(x, y)

"""Задание 2"""

t = np.linspace(0, 10, 51)
f = np.array([np.cos(p) for p in t])
plt.plot(t, f, color='green')
plt.title("График f(t)")
plt.xlabel("Значения t")
plt.ylabel("Значения f")
plt.show()

"""Задание 3"""

x = np.linspace(-3, 3, 51)

y1 = np.array([ x_n ** 2 for x_n in x])
y2 = np.array([ 2 * x_n  + 0.5 for x_n in x])
y3 = np.array([ (-3) * x_n - 1.5 for x_n in x])
y4 = np.array([ np.sin(x_n)  for x_n in x])

fig, ax = plt.subplots(nrows=2, ncols=2)

fig.set_size_inches(8, 6)
fig.subplots_adjust(hspace=0.3, wspace=0.3)

ax[0][0].plot(x, y1)
ax[0][0].set_title('График y1')
ax[0][0].set_xlim(-5, 5)
ax[0][1].plot(x, y2)
ax[0][1].set_title('График y2')
ax[1][0].plot(x, y3)
ax[1][0].set_title('График y3')
ax[1][1].plot(x, y4)
ax[1][1].set_title('График y4')

"""Задание 4"""

import pandas as pd
plt.style.use('fivethirtyeight')

dateframe = pd.read_csv('/content/creditcard.csv')
counts = dateframe['Class'].value_counts()

x = np.linspace(1, 2, 2)
y = [counts[0], counts[1]]

fig, ax = plt.subplots()

ax.bar(x, y)

ax.set_facecolor('seashell')
fig.set_facecolor('floralwhite')
fig.set_figwidth(12)    #  ширина Figure
fig.set_figheight(6)    #  высота Figure

fig, ax = plt.subplots()

ax.bar(x, np.log(y))

ax.set_facecolor('seashell')
fig.set_facecolor('floralwhite')
fig.set_figwidth(12)    #  ширина Figure
fig.set_figheight(6)    #  высота Figure