# -*- coding: utf-8 -*-
"""bib6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wXhOA3ET8jtlooJyu0xx-cwy0o3qMRuQ

Задание 1
"""

import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
boston = load_boston()
data = boston["data"]

feature_names = boston["feature_names"]
X =  pd.DataFrame(data, columns=feature_names)

target = boston["target"]
y = pd.DataFrame(target, columns=["price"]) 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

"""создаем модель"""

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

"""обучаем модель"""

lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})

check_test.head()

"""считаем R2"""

from sklearn.metrics import r2_score

r2_score(check_test["y_pred"], check_test["y_test"])

"""Задание 2"""

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=1000, max_depth=12,  random_state=42)
model.fit(X_train, y_train.values[:, 0])
y_pred = model.predict(X_test)

check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})

r2_score(check_test["y_pred"], check_test["y_test"])

# вторая модель явно справляется лучше, так как у нее ближе коэф детерминации к единице.