# -*- coding: utf-8 -*-
"""bib8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cU0b_9Dge-8ehaYMWkfU-6b_RkMbuOkX

Задание 1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston
boston = load_boston()
data = boston["data"]

feature_names = boston["feature_names"]
X =  pd.DataFrame(data, columns=feature_names)

target = boston["target"]
y = pd.DataFrame(target, columns=["price"]) 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

"""Масштабируем данные"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

"""Построим модель TSNE"""

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, learning_rate=250, random_state=42)
X_train_tsne = tsne.fit_transform(X_train_scaled)

# Здесь же пострим и график

plt.scatter(X_train_tsne[:, 0], X_train_tsne[:, 1])
plt.show()

"""Задание 2"""

from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, random_state=100)

X_train_kMeans = model.fit_predict(X_train_scaled)

# Здесь же пострим и график

centers = scaler.inverse_transform(model.cluster_centers_)

plt.scatter(X_train_tsne[:, 0], X_train_tsne[:, 1], c=X_train_kMeans)
plt.show()

"""считаем средние значения"""

for i in range(3):
  print('Среднее в {}-ом кластере = {} \n'.format(i, y_train[X_train_kMeans == i].mean()))

"""CRIM"""

for i in range(3):
  print('CRIM в {}-ом кластере = {} \n'.format(i, X_train['CRIM'][X_train_kMeans == i].mean()))